spring.datasource.url=jdbc:postgresql://dpg-d6l6co450q8c73bnc4j0-a.oregon-postgres.render.com:5432/cseghrender_db
spring.datasource.username=cseghrender_db_user
spring.datasource.password=S0gu3AmUHnmharNUm6vaIpfley2wzulB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
